var json =[
  {
      "question":"在施工管理系统和人工书面登记办理并行作业期间，以施工管理系统为(  )，人工书面办理为(  )，施工作业调度命令发布及停送电通知单发布均采用软件及人工双轨制办理，并以软件为(  )。",
      "id":1,
      "option":[
          {
              "optionid":"A",
              "content":"辅主主"
          },
          {
              "optionid":"B",
              "content":"辅辅主"
          },
          {
              "optionid":"C",
              "content":"主辅主 "
          },
          {
              "optionid":"D",
              "content":"辅主辅"
          }
      ],
      "answer":"C"
  },
  {
      "question":"对已经报月计划的施工，需要报日补充计划且超过当月各线月计划(  )比率时，由施工归口管理单位与运输管理事业部安技科对接报书面说明材料。",
      "id":2,
      "option":[
          {
              "optionid":"A",
              "content":"0.2"
          },
          {
              "optionid":"B",
              "content":"0.3"
          },
          {
              "optionid":"C",
              "content":"0.4"
          },
          {
              "optionid":"D",
              "content":"0.1"
          }
      ],
      "answer":"A"
  },
  {
      "question":"在基地内进行的项目性施工，原则上由(  ) 负责，但施工方案必须在运输管理事业部生产业务科及调度室报备存档。",
      "id":3,
      "option":[
          {
              "optionid":"A",
              "content":"信号楼调度 "
          },
          {
              "optionid":"B",
              "content":"司机长"
          },
          {
              "optionid":"C",
              "content":"检调 "
          },
          {
              "optionid":"D",
              "content":"派班员"
          }
      ],
      "answer":"A"
  },
  {
      "question":"接触网停电检修或需接触网停电配合挂地线时，由供电操作人员负责在该作业地段两端挂接地线。设置红闪灯的位置应在挂接地线的(  )。",
      "id":4,
      "option":[
          {
              "optionid":"A",
              "content":"内方"
          },
          {
              "optionid":"B",
              "content":"外方 "
          },
          {
              "optionid":"C",
              "content":"适宜地方"
          },
          {
              "optionid":"D",
              "content":"垂直位"
          }
      ],
      "answer":"B"
  },
  {
      "question":"  施工单位在作业期间需要接触网停电或接触网停电挂地线的，应在施工申请表中明确提出配合要求，施工请点时要确认接触网确已停电才能开始作业。如无停电要求，接触网一律视为(  )。",
      "id":5,
      "option":[
          {
              "optionid":"A",
              "content":"无电体"
          },
          {
              "optionid":"B",
              "content":"带电体"
          },
          {
              "optionid":"C",
              "content":"没有停电"
          },
          {
              "optionid":"D",
              "content":"没有送电"
          }
      ],
      "answer":"B"
  },
  {
      "question":"施工负责人在规定施工开始时间前(  )分钟到达主站，按规定程序办理施工作业手续。",
      "id":6,
      "option":[
          {
              "optionid":"A",
              "content":"30"
          },
          {
              "optionid":"B",
              "content":"20"
          },
          {
              "optionid":"C",
              "content":"15"
          },
          {
              "optionid":"D",
              "content":"10"
          }
      ],
      "answer":"C"
  },
  {
      "question":"施工联络人及维修人员在规定施工开始时间前(  )分钟到达辅站，按规定程序办理施工作业手续。",
      "id":7,
      "option":[
          {
              "optionid":"A",
              "content":"10"
          },
          {
              "optionid":"B",
              "content":"15"
          },
          {
              "optionid":"C",
              "content":"20"
          },
          {
              "optionid":"D",
              "content":"30"
          }
      ],
      "answer":"A"
  },
  {
      "question":"在站间线路施工时，除施工部门设置防护外，车站还负责该施工地段两端车站的(  )处设置红闪灯防护【遇特殊情况，因曲线或建筑物遮挡影响瞭望时，防护信号设置地点可适当外移】。",
      "id":8,
      "option":[
          {
              "optionid":"A",
              "content":"轨道中央        "
          },
          {
              "optionid":"B",
              "content":"端墙处"
          },
          {
              "optionid":"C",
              "content":"左侧钢轨上"
          },
          {
              "optionid":"D",
              "content":"右侧钢轨上"
          }
      ],
      "answer":"B"
  },
  {
      "question":"施工分类按照施工作业性质及影响面分为改造类、升级类、(  )类。",
      "id":9,
      "option":[
          {
              "optionid":"A",
              "content":"日常维护"
          },
          {
              "optionid":"B",
              "content":"检修"
          },
          {
              "optionid":"C",
              "content":"硬件"
          },
          {
              "optionid":"D",
              "content":"封锁"
          }
      ],
      "answer":"A"
  },
  {
      "question":" (  )类施工为在正线、辅助线开行电客车、工程列车的施工。",
      "id":10,
      "option":[
          {
              "optionid":"A",
              "content":"A1 "
          },
          {
              "optionid":"B",
              "content":"A2"
          },
          {
              "optionid":"C",
              "content":"A3"
          },
          {
              "optionid":"D",
              "content":"B1 "
          }
      ],
      "answer":"A"
  },
  {
      "question":"(  )类施工为在正线、辅助线不开行电客车、工程列车的施工。",
      "id":11,
      "option":[
          {
              "optionid":"A",
              "content":"A1 "
          },
          {
              "optionid":"B",
              "content":"A2"
          },
          {
              "optionid":"C",
              "content":"A3"
          },
          {
              "optionid":"D",
              "content":"B1 "
          }
      ],
      "answer":"B"
  },
  {
      "question":"(  )类施工为车站、调度大厅及变电所等范围内影响正线、辅助线行车设备设施的施工。",
      "id":12,
      "option":[
          {
              "optionid":"A",
              "content":"A1 "
          },
          {
              "optionid":"B",
              "content":"A2"
          },
          {
              "optionid":"C",
              "content":"A3"
          },
          {
              "optionid":"D",
              "content":"B1 "
          }
      ],
      "answer":"C"
  },
  {
      "question":" 在基地开行电客车、工程列车的施工【不含库内】的施工为(  )。",
      "id":13,
      "option":[
          {
              "optionid":"A",
              "content":"A1 "
          },
          {
              "optionid":"B",
              "content":"B1"
          },
          {
              "optionid":"C",
              "content":"B2"
          },
          {
              "optionid":"D",
              "content":"B3 "
          }
      ],
      "answer":"B"
  },
  {
      "question":"特殊情况下多家施工单位进入同一封锁区间内施工的，由(  )负责防护以及请、销点。",
      "id":14,
      "option":[
          {
              "optionid":"A",
              "content":"值班站长"
          },
          {
              "optionid":"B",
              "content":"值班主任"
          },
          {
              "optionid":"C",
              "content":"各自单位"
          },
          {
              "optionid":"D",
              "content":"主要施工单位"
          }
      ],
      "answer":"D"
  },
  {
      "question":"日补充计划申请表应于工作开始前一天的(   )以前，由各单位编写计划人员收集、调整、汇总后向控制中心调度室施工管理工程师申报。",
      "id":15,
      "option":[
          {
              "optionid":"A",
              "content":"12:00:00"
          },
          {
              "optionid":"B",
              "content":"14:00:00"
          },
          {
              "optionid":"C",
              "content":"16:00:00"
          },
          {
              "optionid":"D",
              "content":"21:00:00"
          }
      ],
      "answer":"A"
  },
  {
      "question":"属于(  )类的作业，无需提报计划，施工负责人与基地信号楼调度员/车站行车值班员/电调/环调等人员联系并登记，经基地信号楼调度员/车站行车值班员/电调等相关人员同意并办理请点手续后开始施工。",
      "id":16,
      "option":[
          {
              "optionid":"A",
              "content":"A3/B3 "
          },
          {
              "optionid":"B",
              "content":"B2/C1 "
          },
          {
              "optionid":"C",
              "content":"B3/C2 "
          },
          {
              "optionid":"D",
              "content":"B3/C3"
          }
      ],
      "answer":"C"
  },
  {
      "question":"同一线路同一施工项目多站进行时，施工联络人到其作业区域包含的各站【除主站外】，登记请点的车站称为辅站；同一施工项目安排主站和辅站原则上不超过(  )个。",
      "id":17,
      "option":[
          {
              "optionid":"A",
              "content":"4"
          },
          {
              "optionid":"B",
              "content":"5"
          },
          {
              "optionid":"C",
              "content":"7"
          },
          {
              "optionid":"D",
              "content":"6"
          }
      ],
      "answer":"D"
  },
  {
      "question":" 施工等级分为：一级施工、二级施工和三级施工。其中(  )是指作业内容复杂、影响面较大、需多部门、多专业联合的施工作业，如新建线路、旧线改造、接触网换线、轨道应力放散、信号系统软件升级等；",
      "id":18,
      "option":[
          {
              "optionid":"A",
              "content":"一级施工"
          },
          {
              "optionid":"B",
              "content":"二级施工"
          },
          {
              "optionid":"C",
              "content":"三级施工"
          },
          {
              "optionid":"D",
              "content":"nan"
          }
      ],
      "answer":"A"
  },
  {
      "question":"正线电客车高速调试计划作业区域两端必须保证至少(  )空闲，不再以一个站台区域作为保护区。连接线、转换轨、联络线等辅助线均可以作为独立的保护分区。",
      "id":19,
      "option":[
          {
              "optionid":"A",
              "content":"一个区间 "
          },
          {
              "optionid":"B",
              "content":"一站一区间"
          },
          {
              "optionid":"C",
              "content":"一站或一区间 "
          },
          {
              "optionid":"D",
              "content":"一站"
          }
      ],
      "answer":"A"
  },
  {
      "question":"原则上，除(  )外，跨线施工作业不予办理延点作业。",
      "id":20,
      "option":[
          {
              "optionid":"A",
              "content":"抢修"
          },
          {
              "optionid":"B",
              "content":"临补计划"
          },
          {
              "optionid":"C",
              "content":"日补充计划"
          },
          {
              "optionid":"D",
              "content":"月计划"
          }
      ],
      "answer":"A"
  },
  {
      "question":"冬运期间，露天部分有钢轨探伤作业，应将车站区域及其相邻(  )米范围内线路的轨面水渍擦拭干净，列车在通过相关施工区段时，行车办法比照上述处理。",
      "id":21,
      "option":[
          {
              "optionid":"A",
              "content":"100"
          },
          {
              "optionid":"B",
              "content":"150"
          },
          {
              "optionid":"C",
              "content":"200"
          },
          {
              "optionid":"D",
              "content":"300"
          }
      ],
      "answer":"C"
  },
  {
      "question":"(  )类计划指局部影响或不影响客运服务，但经采取措施影响不大且动用简单设备设施【如动用220V及以下的电力、钻孔等，不违反安全规定】的施工。",
      "id":22,
      "option":[
          {
              "optionid":"A",
              "content":"C1"
          },
          {
              "optionid":"B",
              "content":"C2"
          },
          {
              "optionid":"C",
              "content":"B2"
          },
          {
              "optionid":"D",
              "content":"A3"
          }
      ],
      "answer":"B"
  },
  {
      "question":"运营期间区间抢修行车设备搭乘客车应得到(  )的批准。",
      "id":23,
      "option":[
          {
              "optionid":"A",
              "content":"值班主任"
          },
          {
              "optionid":"B",
              "content":"行调"
          },
          {
              "optionid":"C",
              "content":"综调"
          },
          {
              "optionid":"D",
              "content":"车站值班员"
          }
      ],
      "answer":"A"
  },
  {
      "question":" 区间风井内作业可能影响正线及辅助线行车的施工，比照A3类作业办理请销点作业。在区间风井设备房内，但不影响行车的施工仍按照(  )类作业，直接与车站/电调办理请销点，车站/电调不向行调请销点。",
      "id":24,
      "option":[
          {
              "optionid":"A",
              "content":"A"
          },
          {
              "optionid":"B",
              "content":"B"
          },
          {
              "optionid":"C",
              "content":"C"
          },
          {
              "optionid":"D",
              "content":"D"
          }
      ],
      "answer":"C"
  },
  {
      "question":"运营期间需开行工程车配合的抢修作业，工程车凭(  )命令进出封锁区域。",
      "id":25,
      "option":[
          {
              "optionid":"A",
              "content":"综调"
          },
          {
              "optionid":"B",
              "content":"行调"
          },
          {
              "optionid":"C",
              "content":"施工负责人"
          },
          {
              "optionid":"D",
              "content":"现场指挥人"
          }
      ],
      "answer":"B"
  },
  {
      "question":"在“问路式”调车时，要求作业人员必须严格执行(  )制度。",
      "id":26,
      "option":[
          {
              "optionid":"A",
              "content":"要道还道 "
          },
          {
              "optionid":"B",
              "content":"双人确认"
          },
          {
              "optionid":"C",
              "content":"呼唤应答"
          },
          {
              "optionid":"D",
              "content":"追问"
          }
      ],
      "answer":"A"
  },
  {
      "question":"需其他部门配合作业的主作业部门，必须按规定的作业时间办理相关手续，超过(  )分钟的，视作该项作业取消，配合部门有权拒绝进行配合。",
      "id":27,
      "option":[
          {
              "optionid":"A",
              "content":"10"
          },
          {
              "optionid":"B",
              "content":"20"
          },
          {
              "optionid":"C",
              "content":"30"
          },
          {
              "optionid":"D",
              "content":"40"
          }
      ],
      "answer":"C"
  },
  {
      "question":"正常施工起点时间应于最后一列回库空客车出清线路、(  )空闲后请点作业。",
      "id":28,
      "option":[
          {
              "optionid":"A",
              "content":"一个区间"
          },
          {
              "optionid":"B",
              "content":"一个站台"
          },
          {
              "optionid":"C",
              "content":"两站两区间"
          },
          {
              "optionid":"D",
              "content":"一站一区间"
          }
      ],
      "answer":"D"
  },
  {
      "question":"为保证施工作业安全，应将线路封锁并限定施工时间的施工不正确的是(  )",
      "id":29,
      "option":[
          {
              "optionid":"A",
              "content":"工程车或调试列车在一个区段多次往返运行或调试车停车配合测试"
          },
          {
              "optionid":"B",
              "content":"网轨检测车在测试区段或钢轨打磨车在打磨区段运行"
          },
          {
              "optionid":"C",
              "content":"更换钢轨【接触网】的施工"
          },
          {
              "optionid":"D",
              "content":"末班车后加开调试列车"
          }
      ],
      "answer":"D"
  },
  {
      "question":"  人、工程车在同一区域作业时，由(  )统一负责。",
      "id":30,
      "option":[
          {
              "optionid":"A",
              "content":"工程车司机"
          },
          {
              "optionid":"B",
              "content":"施工负责人"
          },
          {
              "optionid":"C",
              "content":"施工联络人 "
          },
          {
              "optionid":"D",
              "content":"动车指挥人"
          }
      ],
      "answer":"B"
  },
  {
      "question":"工程车开行规定的主要原则是由(    )负责统一指挥行车。",
      "id":31,
      "option":[
          {
              "optionid":"A",
              "content":"值班主任"
          },
          {
              "optionid":"B",
              "content":"调度长"
          },
          {
              "optionid":"C",
              "content":"行调  "
          },
          {
              "optionid":"D",
              "content":"施工负责人"
          }
      ],
      "answer":"C"
  },
  {
      "question":"运营期间在正线需开行工程车进行施工抢修时，施工负责人需向(    )申请，并经分管副总同意后，由值班主任指定专人负责开行事宜。",
      "id":32,
      "option":[
          {
              "optionid":"A",
              "content":"运输管理事业部部长"
          },
          {
              "optionid":"B",
              "content":"调度室值班主任"
          },
          {
              "optionid":"C",
              "content":"行车调度"
          },
          {
              "optionid":"D",
              "content":"综合调度"
          }
      ],
      "answer":"B"
  },
  {
      "question":"设备设施发生故障需立即进行抢修的作业，需提报(  )。",
      "id":33,
      "option":[
          {
              "optionid":"A",
              "content":"月计划"
          },
          {
              "optionid":"B",
              "content":"日补充计划"
          },
          {
              "optionid":"C",
              "content":"临时抢修计划 "
          },
          {
              "optionid":"D",
              "content":"临时补充计划"
          }
      ],
      "answer":"C"
  },
  {
      "question":"凡是施工作业包含联络线、不同线路轨行区或不同线路设备房【变电所】的施工，均定义为(    )。",
      "id":34,
      "option":[
          {
              "optionid":"A",
              "content":"封锁施工"
          },
          {
              "optionid":"B",
              "content":"临时施工"
          },
          {
              "optionid":"C",
              "content":"跨线施工"
          },
          {
              "optionid":"D",
              "content":"联合施工"
          }
      ],
      "answer":"C"
  },
  {
      "question":"施工计划中如果没有注明不含车站，即(  )车站；基地内作业如果没有注明含库内，即(      )库内。",
      "id":35,
      "option":[
          {
              "optionid":"A",
              "content":"含，不含"
          },
          {
              "optionid":"B",
              "content":"不含，不含"
          },
          {
              "optionid":"C",
              "content":"含，含  "
          },
          {
              "optionid":"D",
              "content":"不含，含"
          }
      ],
      "answer":"A"
  },
  {
      "question":"影响正线的抢修计划、临时补修计划由当班值班主任负责，行调根据(  )提供的故障号，进行施工作业审批。",
      "id":36,
      "option":[
          {
              "optionid":"A",
              "content":"综调"
          },
          {
              "optionid":"B",
              "content":"车站"
          },
          {
              "optionid":"C",
              "content":"值班主任"
          },
          {
              "optionid":"D",
              "content":"环调"
          }
      ],
      "answer":"A"
  },
  {
      "question":"影响面较小、多专业联合的施工作业，如道岔更换、多辆工程车配合的施工属于（  ）施工。",
      "id":37,
      "option":[
          {
              "optionid":"A",
              "content":"一级    "
          },
          {
              "optionid":"B",
              "content":"二级 "
          },
          {
              "optionid":"C",
              "content":"三级"
          },
          {
              "optionid":"D",
              "content":"以上都不是"
          }
      ],
      "answer":"B"
  },
  {
      "question":"每项属于A类、B类、C类（B3、C2除外）作业需设立一名（  ）。",
      "id":38,
      "option":[
          {
              "optionid":"A",
              "content":"施工负责人"
          },
          {
              "optionid":"B",
              "content":"施工联络人"
          },
          {
              "optionid":"C",
              "content":"抢修负责人"
          },
          {
              "optionid":"D",
              "content":"调试负责人"
          }
      ],
      "answer":"A"
  },
  {
      "question":"负责在主站办理作业登记和该项作业的组织、安全和管理的人员是（   ）。",
      "id":39,
      "option":[
          {
              "optionid":"A",
              "content":"施工负责人"
          },
          {
              "optionid":"B",
              "content":"施工联络人"
          },
          {
              "optionid":"C",
              "content":"抢修负责人"
          },
          {
              "optionid":"D",
              "content":"调试负责人"
          }
      ],
      "answer":"A"
  },
  {
      "question":"所有施工，遇特殊情况需延长施工作业的时间时，施工负责人应在计划结束前的（   ）分钟向行车值班员/信号楼调度员请示。",
      "id":40,
      "option":[
          {
              "optionid":"A",
              "content":"60"
          },
          {
              "optionid":"B",
              "content":"30"
          },
          {
              "optionid":"C",
              "content":"15"
          },
          {
              "optionid":"D",
              "content":"20"
          }
      ],
      "answer":"B"
  },
  {
      "question":"擅自取消作业指在作业前 （     ）小时，施工负责人或受委托人未向总调中心或归口管理单位申请同意而擅自取消施工计划。",
      "id":41,
      "option":[
          {
              "optionid":"A",
              "content":"1"
          },
          {
              "optionid":"B",
              "content":"半"
          },
          {
              "optionid":"C",
              "content":"2"
          },
          {
              "optionid":"D",
              "content":"3"
          }
      ],
      "answer":"D"
  },
  {
      "question":"施工请点时确认（   ）已停电或已挂好地线方可作业。",
      "id":42,
      "option":[
          {
              "optionid":"A",
              "content":"接触网  "
          },
          {
              "optionid":"B",
              "content":"照明 "
          },
          {
              "optionid":"C",
              "content":"空调"
          },
          {
              "optionid":"D",
              "content":"nan"
          }
      ],
      "answer":"A"
  },
  {
      "question":"需其他单位配合的作业，作业单位必须按规定的时间办理手续，无特殊情况，超过（  ）分钟未办理手续的，视作该项作业取消，配合单位有权拒绝进行配合。",
      "id":43,
      "option":[
          {
              "optionid":"A",
              "content":"60 "
          },
          {
              "optionid":"B",
              "content":"30"
          },
          {
              "optionid":"C",
              "content":"15"
          },
          {
              "optionid":"D",
              "content":"20"
          }
      ],
      "answer":"B"
  },
  {
      "question":"（   ）负责与外单位签订《外单位施工安全、消防、治安内保协议书》。",
      "id":44,
      "option":[
          {
              "optionid":"A",
              "content":"安全保卫部 "
          },
          {
              "optionid":"B",
              "content":"技术部"
          },
          {
              "optionid":"C",
              "content":"运输管理部"
          },
          {
              "optionid":"D",
              "content":"财务审计部"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工工具物料由（   ）负责清点、管理，销点清单留存在销点站备案。",
      "id":45,
      "option":[
          {
              "optionid":"A",
              "content":"施工负责人"
          },
          {
              "optionid":"B",
              "content":"施工联络人"
          },
          {
              "optionid":"C",
              "content":"抢修负责人"
          },
          {
              "optionid":"D",
              "content":"调试负责人"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工区域出清指在施工区域范围内，施工结束后，施工负责人或施工联络人确认所有作业有关人员已撤离、有关设备设施已恢复正常、(   )已撤走、无妨碍行车和设备安全的因素等。",
      "id":46,
      "option":[
          {
              "optionid":"A",
              "content":"工器具"
          },
          {
              "optionid":"B",
              "content":"物料"
          },
          {
              "optionid":"C",
              "content":"工器具、物料"
          },
          {
              "optionid":"D",
              "content":"nan"
          }
      ],
      "answer":"C"
  },
  {
      "question":"按施工前进方向,列车在（）,人员在（）,原则上不得颠倒。",
      "id":47,
      "option":[
          {
              "optionid":"A",
              "content":"后、前"
          },
          {
              "optionid":"B",
              "content":"前、后"
          },
          {
              "optionid":"C",
              "content":"左、右"
          },
          {
              "optionid":"D",
              "content":"右、左"
          }
      ],
      "answer":"B"
  },
  {
      "question":"非随车施工人员与列车应有（  ）米以上的安全间隔距离，原则上列车不得随意后退，需退行时，车长（司机）应听从现场施工负责人的指挥，按要求退行，确保人身安全；",
      "id":48,
      "option":[
          {
              "optionid":"A",
              "content":"40"
          },
          {
              "optionid":"B",
              "content":"50"
          },
          {
              "optionid":"C",
              "content":"60"
          },
          {
              "optionid":"D",
              "content":"70"
          }
      ],
      "answer":"B"
  },
  {
      "question":"人、工程车在同一区域作业时，作业人员应在作业区域（ ）方向设置红闪灯防护。",
      "id":49,
      "option":[
          {
              "optionid":"A",
              "content":"内方"
          },
          {
              "optionid":"B",
              "content":"外方"
          },
          {
              "optionid":"C",
              "content":"来车"
          },
          {
              "optionid":"D",
              "content":"两端"
          }
      ],
      "answer":"C"
  },
  {
      "question":"人、工程车在同一区域作业时，由施工负责人统一负责，需要动车时，由（  ）向司机下达指令，司机按正确的指令执行。",
      "id":50,
      "option":[
          {
              "optionid":"A",
              "content":"施工负责人"
          },
          {
              "optionid":"B",
              "content":"施工联络人  "
          },
          {
              "optionid":"C",
              "content":"抢修负责人"
          },
          {
              "optionid":"D",
              "content":"调试负责人"
          }
      ],
      "answer":"A"
  },
  {
      "question":"固定作业地点的作业，施工单位负责在施工区域两端的（  ）设置红闪灯或派专人防护。",
      "id":51,
      "option":[
          {
              "optionid":"A",
              "content":"轨枕上"
          },
          {
              "optionid":"B",
              "content":"轨行区"
          },
          {
              "optionid":"C",
              "content":"轨道一侧 "
          },
          {
              "optionid":"D",
              "content":"轨道中央"
          }
      ],
      "answer":"D"
  },
  {
      "question":"施工过程中如要进行动火作业，必须按照宁铁安字[2004]第153号文《南京地铁有限责任公司运营公司消防安全管理制度（试行）》办理（ ）及作业，严禁在无动火令的情况下进行动火作业。",
      "id":52,
      "option":[
          {
              "optionid":"A",
              "content":"施工计划"
          },
          {
              "optionid":"B",
              "content":"施工请点"
          },
          {
              "optionid":"C",
              "content":"施工登记"
          },
          {
              "optionid":"D",
              "content":"动火令"
          }
      ],
      "answer":"D"
  },
  {
      "question":"《施工负责人考核管理办法》规定施工负责人每年每人计（  ）分。",
      "id":53,
      "option":[
          {
              "optionid":"A",
              "content":"15"
          },
          {
              "optionid":"B",
              "content":"12"
          },
          {
              "optionid":"C",
              "content":"10"
          },
          {
              "optionid":"D",
              "content":"30"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工负责人合格证有效期为（  ）年 。",
      "id":54,
      "option":[
          {
              "optionid":"A",
              "content":"1"
          },
          {
              "optionid":"B",
              "content":"2"
          },
          {
              "optionid":"C",
              "content":"3"
          },
          {
              "optionid":"D",
              "content":"半"
          }
      ],
      "answer":"A"
  },
  {
      "question":"因违规施工导致一次考核15分的，（  ）年内不得申请施工负责人合格证。 ",
      "id":55,
      "option":[
          {
              "optionid":"A",
              "content":"1"
          },
          {
              "optionid":"B",
              "content":"2"
          },
          {
              "optionid":"C",
              "content":"3"
          },
          {
              "optionid":"D",
              "content":"半"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工负责人到某个车站登记请点施工的车站称为(   )",
      "id":56,
      "option":[
          {
              "optionid":"A",
              "content":"终点站"
          },
          {
              "optionid":"B",
              "content":"辅站"
          },
          {
              "optionid":"C",
              "content":"主站"
          },
          {
              "optionid":"D",
              "content":"起始站"
          }
      ],
      "answer":"C"
  },
  {
      "question":"安全避让区域指的是不侵入线路机车车辆限界，并确保抢修人员站立及抢修工具的存放有足够的（   ）。",
      "id":57,
      "option":[
          {
              "optionid":"A",
              "content":"空闲区间"
          },
          {
              "optionid":"B",
              "content":"安全空间"
          },
          {
              "optionid":"C",
              "content":"轨行区"
          },
          {
              "optionid":"D",
              "content":"地点"
          }
      ],
      "answer":"B"
  },
  {
      "question":"一级施工由（   ）牵头召开专题施工协调会进行协调落实施工有关安排。",
      "id":58,
      "option":[
          {
              "optionid":"A",
              "content":"分管领导"
          },
          {
              "optionid":"B",
              "content":"公司分管领导"
          },
          {
              "optionid":"C",
              "content":"主管施工的领导"
          },
          {
              "optionid":"D",
              "content":"公司主管施工的领导"
          }
      ],
      "answer":"B"
  },
  {
      "question":"二级施工由（   ）或分管领导委托中心负责牵头召开专题施工协调会进行协调落实施工有关安排。",
      "id":59,
      "option":[
          {
              "optionid":"A",
              "content":"分管领导"
          },
          {
              "optionid":"B",
              "content":"公司分管领导"
          },
          {
              "optionid":"C",
              "content":"主管施工的领导"
          },
          {
              "optionid":"D",
              "content":"公司主管施工的领导"
          }
      ],
      "answer":"A"
  },
  {
      "question":"（   ）施工相关配合单位须拟写施工配合方案，由归口管理单位牵头审核。",
      "id":60,
      "option":[
          {
              "optionid":"A",
              "content":"三级"
          },
          {
              "optionid":"B",
              "content":"二级"
          },
          {
              "optionid":"C",
              "content":"一级"
          },
          {
              "optionid":"D",
              "content":"一、二级"
          }
      ],
      "answer":"D"
  },
  {
      "question":"三级施工配合单位须在（  ）签署施工配合意见。",
      "id":61,
      "option":[
          {
              "optionid":"A",
              "content":"施工计划许可单"
          },
          {
              "optionid":"B",
              "content":"施工计划申请单"
          },
          {
              "optionid":"C",
              "content":"行车通报"
          },
          {
              "optionid":"D",
              "content":"施工方案申报表"
          }
      ],
      "answer":"D"
  },
  {
      "question":"正线更换 3 副及以上道岔，属于（   ）施工。",
      "id":62,
      "option":[
          {
              "optionid":"A",
              "content":"改造类"
          },
          {
              "optionid":"B",
              "content":"日常维护类"
          },
          {
              "optionid":"C",
              "content":"升级类     "
          },
          {
              "optionid":"D",
              "content":"其他"
          }
      ],
      "answer":"A"
  },
  {
      "question":"更换钢轨超过 300 米以上、轨道应力放散，属于（ A ）施工。",
      "id":63,
      "option":[
          {
              "optionid":"A",
              "content":"改造类"
          },
          {
              "optionid":"B",
              "content":"日常维护类"
          },
          {
              "optionid":"C",
              "content":"升级类     "
          },
          {
              "optionid":"D",
              "content":"其他"
          }
      ],
      "answer":"A"
  },
  {
      "question":"对行车有较大影响的施工应该提报（   ）。",
      "id":64,
      "option":[
          {
              "optionid":"A",
              "content":"月计划"
          },
          {
              "optionid":"B",
              "content":"日补充计划"
          },
          {
              "optionid":"C",
              "content":"临时补修计划"
          },
          {
              "optionid":"D",
              "content":"临时抢修"
          }
      ],
      "answer":"A"
  },
  {
      "question":"运营时间内在车站公共区域进行的影响运营服务的施工检修作业应该提报（   ）",
      "id":65,
      "option":[
          {
              "optionid":"A",
              "content":"月计划"
          },
          {
              "optionid":"B",
              "content":"日补充计划"
          },
          {
              "optionid":"C",
              "content":"临时补修计划"
          },
          {
              "optionid":"D",
              "content":"临时抢修"
          }
      ],
      "answer":"A"
  },
  {
      "question":"日补充计划申报的作业项目原则上不得超过同期同类月计划内日作业项目的（  ），施工计划因特殊情况需变动以《计划变更表》的形式提报。",
      "id":66,
      "option":[
          {
              "optionid":"A",
              "content":"15% "
          },
          {
              "optionid":"B",
              "content":"20%"
          },
          {
              "optionid":"C",
              "content":"25%"
          },
          {
              "optionid":"D",
              "content":"30%"
          }
      ],
      "answer":"B"
  },
  {
      "question":"人、工程车在同一区域作业时，由施工负责人统一负责，动车时，由（）向司机下达指令，司机按正确的指令执行。",
      "id":67,
      "option":[
          {
              "optionid":"A",
              "content":"施工负责人"
          },
          {
              "optionid":"B",
              "content":"施工联络人"
          },
          {
              "optionid":"C",
              "content":"抢修负责人"
          },
          {
              "optionid":"D",
              "content":"调试负责人"
          }
      ],
      "answer":"A"
  },
  {
      "question":"属于 A 类作业，但需由多个车站进入施工的作业项目，施工负责人除到主站按照规定办理相关手续外，另需核实（  ）情况。",
      "id":68,
      "option":[
          {
              "optionid":"A",
              "content":"辅站"
          },
          {
              "optionid":"B",
              "content":"两端站"
          },
          {
              "optionid":"C",
              "content":"包含站"
          },
          {
              "optionid":"D",
              "content":"有岔站"
          }
      ],
      "answer":"A"
  },
  {
      "question":"轨行区的施工作业，销点作业时，施工负责人持（   ）交销点站备案，施工负责人按车站要求将施工工器具、物料放规定区域，用车站指定编号 CCTV 摄像头拍摄施工工器具、物料，施工工器具、物料由施工负责人专人负责清点、管理。",
      "id":69,
      "option":[
          {
              "optionid":"A",
              "content":"施工工器具清单"
          },
          {
              "optionid":"B",
              "content":"物料清单"
          },
          {
              "optionid":"C",
              "content":"施工负责人合格证"
          },
          {
              "optionid":"D",
              "content":"施工工器具、物料清单"
          }
      ],
      "answer":"D"
  },
  {
      "question":"当施工作业有多组人员进行，需异地销点的，施工负责人统一向在（  ）登记的销点站登记销点，销点站经与施工负责人核对销点的施工内容、施工人数、地点全部无误后，记录作业代码、作业人数、施工负责人等，并向请点站核对无误后，准予销点，销点站向请点站销完点后负责向行调报告销点。",
      "id":70,
      "option":[
          {
              "optionid":"A",
              "content":"辅站 "
          },
          {
              "optionid":"B",
              "content":"两端站"
          },
          {
              "optionid":"C",
              "content":"主站"
          },
          {
              "optionid":"D",
              "content":"有岔站"
          }
      ],
      "answer":"C"
  },
  {
      "question":"当一项施工作业需要包括多个作业地点时，可以安排2名施工负责人分别负责。",
      "id":71,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"因特殊情况不能按时完工时，施工负责人应在原定施工截止时间前10分钟与调度员联系，得到批准后方可延长作业时间。",
      "id":72,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工计划中如果没有注明不含车站，即不含车站。",
      "id":73,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"人工巡道的周期间隔不得超过48小时。",
      "id":74,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"封锁区域工程车运行由行调负责指挥。",
      "id":75,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"同一线路同一施工项目多站进行时，施工联络人到其作业区域包含的各站【除主站外】，登记请点的车站称为辅站；同一施工项目安排主站和辅站原则上不超过5个。",
      "id":76,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"施工计划按时间可分为：月计划、日补充计划、临时补充计划。",
      "id":77,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"同一线路同一施工项目多站进行时，施工联络人到其作业区域登记请点的车站称为主站。",
      "id":78,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"冬运期间，露天部分有钢轨探伤作业，应将车站区域及其相邻300米范围内线路的轨面水渍擦拭干净。",
      "id":79,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"封锁区域内工程车运行由施工负责人负责指挥。",
      "id":80,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"外单位指除南京地铁运营有限责任公司以外的单位。",
      "id":81,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"外单位施工进场凭证：《外单位施工作业许可单》、施工负责人培训合格证",
      "id":82,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"施工过程中如要进行动火作业，必须按消防安全管理制度办理动火令及作业，严禁在无动火令的情况下进行动火作业。",
      "id":83,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"跨线施工指的是施工作业包含联络线、不同线路轨行区或不同线路设备房（变电所）的施工，均定义为跨线施工。",
      "id":84,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"按照施工作业性质及影响面分为改造类、升级类、日常维护类。",
      "id":85,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"按施工影响范围分为：一级施工、二级施工和其他级施工。",
      "id":86,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"工程车或调试列车在一个区段多次往返运行或调试车停车配合测试须封锁线路并限定施工时间。",
      "id":87,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"网轨检测车在测试区段或钢轨打磨车在打磨区段运行不需要封锁线路。",
      "id":88,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"A"
  },
  {
      "question":"对于更换钢轨（接触网），无论有无工程车开行，均须将所占用线路封锁。",
      "id":89,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  },
  {
      "question":"计划兑现率是指各类计划中实际完成件数与计划件数的比值。",
      "id":90,
      "option":[
          {
              "optionid":"A",
              "content":"X"
          },
          {
              "optionid":"B",
              "content":"√"
          }
      ],
      "answer":"B"
  }
]

module.exports = {
  sgfzr:json
}